version: "3.9"
services:
  superftp:
    build: .
    ports: 
       - "20:20"
       - "21:21"
       - "60000-60100:60000-60100"

    env_file:
      - env.list

    volumes:
      - ./vsftpd.key:/etc/ssl/private/vsftpd.key 
      - ./vsftpd.crt:/etc/ssl/certs/vsftpd.crt 
      - ./ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key 
      - ./ssh_host_dsa_key:/etc/ssh/ssh_host_dsa_key

    devices:
      - "/dev/fuse"

    cap_add:
      - "SYS_ADMIN"

    logging:
      driver: ${LOG_DRIVER}
      options:
        loki-url: ${LOKI_URL}
        labels: container_name,host

